name: Format-check

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "clang-format-14"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: b.i.o.
          fetch-depth: 2
          submodules: recursive

      - name: Add package source
        run: |
          echo 'APT::Acquire::Retries "5";' | sudo tee -a /etc/apt/apt.conf.d/80-retries > /dev/null
          sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo add-apt-repository --no-update --yes "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main"
          sudo apt-get update

      - name: Install CMake
        run: sudo apt-get install --yes cmake

      - name: Install clang-format ${{ matrix.name }}
        run: sudo apt-get install --yes ${{ matrix.name }}

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.name }} --version

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir build
          cd build
          cmake ../b.i.o./test/format

      - name: Run tests
        run: |
          cd build
          make check_library
          make check_unit_tests
